# ---------------------------------------------------------------------,
# Waveform Configuration
# ---------------------------------------------------------------------,
standard: "matwaves"

bandwidth: 10.0e+6
sample_rate: 30.72e+3

